<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_j8C4sIPbEeqXlKUduLqENg" name="Processo_Compra" author="Lovelace" bonitaVersion="7.10.4" bonitaModelVersion="7.10.0-001" configId="ACED0005740010372E31302E302D303031372E31302E34">
    <elements xmi:type="process:Pool" xmi:id="_j8C4sYPbEeqXlKUduLqENg" name="Processo Compra">
      <elements xmi:type="process:Lane" xmi:id="_j8C4soPbEeqXlKUduLqENg" name="Colaborador" actor="_j8C4y4PbEeqXlKUduLqENg">
        <elements xmi:type="process:StartEvent" xmi:id="_j8C4s4PbEeqXlKUduLqENg" name="Necessidade de um produto" outgoing="_jlBDUIPcEeqXlKUduLqENg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j8C4tIPbEeqXlKUduLqENg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j8C4tYPbEeqXlKUduLqENg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j8C4toPbEeqXlKUduLqENg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_j8C4t4PbEeqXlKUduLqENg" name="Indroduzir dados" outgoing="_gp7scIklEeqCs6_Zt3VV5Q" incoming="_x1en4IkkEeqCs6_Zt3VV5Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j8C4uIPbEeqXlKUduLqENg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j8C4uYPbEeqXlKUduLqENg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j8C4uoPbEeqXlKUduLqENg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_dUqC54sLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dUqC6IsLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dUqC6YsLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos">
                <defaultValue xmi:type="expression:Expression" xmi:id="_l5mqAIsMEeqHHvcBOa57dw" name="initCompraPedido()" content="def comprasPedidosVar = new com.company.model.comprasPedidos()&#xD;&#xA;comprasPedidosVar.compraID = BonitaUsers.getProcessInstanceInitiator(apiAccessor, processInstanceId).id&#xD;&#xA;comprasPedidosVar.status = &quot;pendente&quot; &#xD;&#xA;comprasPedidosVar.dataCompra =      ?.dataCompra&#xD;&#xA;comprasPedidosVar.nomeCompra =      ?.nomeCompra&#xD;&#xA;comprasPedidosVar.numCompromisso =      ?.numCompromisso?.trim() ?      .numCompromisso.toLong() : null&#xD;&#xA;comprasPedidosVar.temCabimento =      ?.temCabimento&#xD;&#xA;comprasPedidosVar.numCabimento =      ?.numCabimento?.trim() ?      .numCabimento.toLong() : null&#xD;&#xA;comprasPedidosVar.valorCompra =      ?.valorCompra?.toFloat()&#xD;&#xA;return comprasPedidosVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.comprasPedidos">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_l5mqAYsMEeqHHvcBOa57dw" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_l5mqAosMEeqHHvcBOa57dw" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
                </defaultValue>
              </referencedElements>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dUqC6osLEeqHHvcBOa57dw" name="compraPedidoInput.dataPedido" content="     ?.dataPedido" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate"/>
            <operator xmi:type="expression:Operator" xmi:id="_dUqC7IsLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setDataPedido">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_dUqC7YsLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dUqC7osLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dUqC74sLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dUqC8IsLEeqHHvcBOa57dw" name="compraPedidoInput.nomeCompra" content="     ?.nomeCompra" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_dUqC8osLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setNomeCompra">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_dUqC84sLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dUqC9IsLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dUqC9YsLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dUqC9osLEeqHHvcBOa57dw" name="compraPedidoInput.numCompromisso" content="     ?.numCompromisso?.trim() ?      .numCompromisso.toLong() : null" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
            <operator xmi:type="expression:Operator" xmi:id="_dUqC-IsLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setNumCompromisso">
              <inputTypes>java.lang.Long</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_dUqC-YsLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dUqC-osLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dUqC-4sLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dUqC_IsLEeqHHvcBOa57dw" name="compraPedidoInput.temCabimento" content="     ?.temCabimento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean"/>
            <operator xmi:type="expression:Operator" xmi:id="_dUqC_osLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setTemCabimento">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_dUqC_4sLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dUqDAIsLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dUqDAYsLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dUqDAosLEeqHHvcBOa57dw" name="compraPedidoInput.numCabimento" content="     ?.numCabimento?.trim() ?      .numCabimento.toLong() : null" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
            <operator xmi:type="expression:Operator" xmi:id="_dUqDBIsLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setNumCabimento">
              <inputTypes>java.lang.Long</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_dUqDBYsLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dUqDBosLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dUqDB4sLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dUqDCIsLEeqHHvcBOa57dw" name="compraPedidoInput.valorCompra" content="     ?.valorCompra?.toFloat()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Float"/>
            <operator xmi:type="expression:Operator" xmi:id="_dUqDCosLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setValorCompra">
              <inputTypes>java.lang.Float</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gho8QIsLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gho8QYsLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gho8QosLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gho8Q4sLEeqHHvcBOa57dw" name="compraPedidoInput.dataPedido" content="compraPedidoInput?.dataPedido" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gho8RIsLEeqHHvcBOa57dw" name="compraPedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gho8RYsLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setDataPedido">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gho8RosLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gho8R4sLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gho8SIsLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gho8SYsLEeqHHvcBOa57dw" name="compraPedidoInput.nomeCompra" content="compraPedidoInput?.nomeCompra" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gho8SosLEeqHHvcBOa57dw" name="compraPedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gho8S4sLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setNomeCompra">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gho8TIsLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gho8TYsLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gho8TosLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gho8T4sLEeqHHvcBOa57dw" name="compraPedidoInput.numCompromisso" content="compraPedidoInput?.numCompromisso?.trim() ? compraPedidoInput.numCompromisso.toLong() : null" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gho8UIsLEeqHHvcBOa57dw" name="compraPedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gho8UYsLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setNumCompromisso">
              <inputTypes>java.lang.Long</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gho8UosLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gho8U4sLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gho8VIsLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gho8VYsLEeqHHvcBOa57dw" name="compraPedidoInput.temCabimento" content="compraPedidoInput?.temCabimento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gho8VosLEeqHHvcBOa57dw" name="compraPedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gho8V4sLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setTemCabimento">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gho8WIsLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gho8WYsLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gho8WosLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gho8W4sLEeqHHvcBOa57dw" name="compraPedidoInput.numCabimento" content="compraPedidoInput?.numCabimento?.trim() ? compraPedidoInput.numCabimento.toLong() : null" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gho8XIsLEeqHHvcBOa57dw" name="compraPedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gho8XYsLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setNumCabimento">
              <inputTypes>java.lang.Long</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gho8XosLEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gho8X4sLEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gho8YIsLEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gho8YYsLEeqHHvcBOa57dw" name="compraPedidoInput.valorCompra" content="compraPedidoInput?.valorCompra?.toFloat()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Float">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gho8YosLEeqHHvcBOa57dw" name="compraPedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gho8Y4sLEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setValorCompra">
              <inputTypes>java.lang.Float</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_j8C4u4PbEeqXlKUduLqENg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_j8C4vIPbEeqXlKUduLqENg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_j8C4vYPbEeqXlKUduLqENg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_j8C4voPbEeqXlKUduLqENg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_j8C4v4PbEeqXlKUduLqENg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_j8C4wIPbEeqXlKUduLqENg">
            <targetForm xmi:type="expression:Expression" xmi:id="_j8C4wYPbEeqXlKUduLqENg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_j8C4woPbEeqXlKUduLqENg">
            <inputs xmi:type="process:ContractInput" xmi:id="_ghoVMIsLEeqHHvcBOa57dw" name="compraPedidoInput" type="COMPLEX" dataReference="compraPedido" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_ghoVMYsLEeqHHvcBOa57dw" name="dataPedido" type="LOCALDATE" description="Data em que o pedido de compra foi efetuado" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ghoVMosLEeqHHvcBOa57dw" name="nomeCompra" description="Nome da compra a pagar" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ghoVM4sLEeqHHvcBOa57dw" name="numCompromisso" description="Número de compromisso associado à compra" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ghoVNIsLEeqHHvcBOa57dw" name="temCabimento" type="BOOLEAN" description="Se este pagamento tem cabimento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ghoVNYsLEeqHHvcBOa57dw" name="numCabimento" description="Número de cabimento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ghoVNosLEeqHHvcBOa57dw" name="valorCompra" type="DECIMAL" description="Valor a pagar" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_ghoVN4sLEeqHHvcBOa57dw" expression="compraPedidoInput?.dataPedido != null" errorMessage="dataPedido is mandatory for comprasPedidos" name="mandatory_compraPedidoInput_dataPedido">
              <inputNames>compraPedidoInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_ghoVOIsLEeqHHvcBOa57dw" expression="compraPedidoInput?.nomeCompra != null" errorMessage="nomeCompra is mandatory for comprasPedidos" name="mandatory_compraPedidoInput_nomeCompra">
              <inputNames>compraPedidoInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_ghoVOYsLEeqHHvcBOa57dw" expression="compraPedidoInput?.numCompromisso != null" errorMessage="numCompromisso is mandatory for comprasPedidos" name="mandatory_compraPedidoInput_numCompromisso">
              <inputNames>compraPedidoInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_ghoVOosLEeqHHvcBOa57dw" expression="!compraPedidoInput?.numCompromisso || compraPedidoInput?.numCompromisso.isLong()" errorMessage="A Long value is expected for comprasPedidos.numCompromisso" name="type_long_compraPedidoInput_numCompromisso">
              <inputNames>compraPedidoInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_ghoVO4sLEeqHHvcBOa57dw" expression="compraPedidoInput?.temCabimento != null" errorMessage="temCabimento is mandatory for comprasPedidos" name="mandatory_compraPedidoInput_temCabimento">
              <inputNames>compraPedidoInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_ghoVPIsLEeqHHvcBOa57dw" expression="!compraPedidoInput?.numCabimento || compraPedidoInput?.numCabimento.isLong()" errorMessage="A Long value is expected for comprasPedidos.numCabimento" name="type_long_compraPedidoInput_numCabimento">
              <inputNames>compraPedidoInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_ghoVPYsLEeqHHvcBOa57dw" expression="compraPedidoInput?.valorCompra != null" errorMessage="valorCompra is mandatory for comprasPedidos" name="mandatory_compraPedidoInput_valorCompra">
              <inputNames>compraPedidoInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_lKFuEIsLEeqHHvcBOa57dw" expression="compraPedidoInput.dataPedido.isAfter(java.time.LocalDate.now())&#xD;&#xA;return true;" errorMessage="Pagamento da compra tem que ser efetuado no futuro" name="pagamentoNoFuturo">
              <inputNames>compraPedidoInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_20fTQIsLEeqHHvcBOa57dw" expression="compraPedidoInput.valorCompra > 0&#xD;&#xA;return true;" errorMessage="O valor a pagar tem que ser maior que zero" name="valorAPagarMaiorQueZero">
              <inputNames>compraPedidoInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_j8C4w4PbEeqXlKUduLqENg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_g_6CQIPcEeqXlKUduLqENg" outgoing="_x1en4IkkEeqCs6_Zt3VV5Q" incoming="_jlBDUIPcEeqXlKUduLqENg _k00YgIklEeqCs6_Zt3VV5Q _NX-MMIkoEeqCs6_Zt3VV5Q _GKBF0IkqEeqCs6_Zt3VV5Q _n2KLUIlhEeqm0fYUL6Uqjg _p9cn8IlhEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_g_6CQoPcEeqXlKUduLqENg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_g_6CQYPcEeqXlKUduLqENg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_g_6CQ4PcEeqXlKUduLqENg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_GE4YQIlYEeqm0fYUL6Uqjg" name="Informar fornecedor" outgoing="_W_ffQIlYEeqm0fYUL6Uqjg" incoming="_N89HwIlYEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4FCZQolXEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4FCZQYlXEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4FCZQ4lXEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4FDAUIlXEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4FDAUYlXEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4FDAUolXEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4FDAVIlXEeqm0fYUL6Uqjg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4FDAU4lXEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_TGM5gIlYEeqm0fYUL6Uqjg" name="Compra finalizada" incoming="_W_ffQIlYEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TGNgkYlYEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TGNgkIlYEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TGNgkolYEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_6nQsYIPbEeqXlKUduLqENg" name="Responsável pelo CR">
        <elements xmi:type="process:Task" xmi:id="__tHGEIkkEeqCs6_Zt3VV5Q" name="Dar justificação" outgoing="_Wi_KQIkoEeqCs6_Zt3VV5Q" incoming="_eauGEIkpEeqCs6_Zt3VV5Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__tHtIYkkEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__tHtIIkkEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__tHtIokkEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__tHtI4kkEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__tHtJIkkEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__tHtJYkkEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__tHtJ4kkEeqCs6_Zt3VV5Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__tHtJokkEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__tHtKYkkEeqCs6_Zt3VV5Q">
            <targetForm xmi:type="expression:Expression" xmi:id="__tHtKokkEeqCs6_Zt3VV5Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__tHtKIkkEeqCs6_Zt3VV5Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__tHtK4kkEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_GMGiwIklEeqCs6_Zt3VV5Q" name="Despesa valida?" outgoing="_jLzzUIklEeqCs6_Zt3VV5Q _ES2FoIkmEeqCs6_Zt3VV5Q" incoming="_yH7NUIklEeqCs6_Zt3VV5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GMHJ0YklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GMHJ0IklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GMHJ0oklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_GjV-EIklEeqCs6_Zt3VV5Q" outgoing="_k00YgIklEeqCs6_Zt3VV5Q _wNhWIIklEeqCs6_Zt3VV5Q" incoming="_jLzzUIklEeqCs6_Zt3VV5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GjV-EoklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GjV-EYklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GjV-E4klEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ruQ8kIklEeqCs6_Zt3VV5Q" name="Cancelar AD" incoming="_wNhWIIklEeqCs6_Zt3VV5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ruQ8koklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ruQ8kYklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ruQ8k4klEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ruQ8lIklEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ruQ8lYklEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ruQ8loklEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ruQ8mIklEeqCs6_Zt3VV5Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ruQ8l4klEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_J6atMIsKEeqHHvcBOa57dw" name="Validar despesa" outgoing="_yH7NUIklEeqCs6_Zt3VV5Q" incoming="_gp7scIklEeqCs6_Zt3VV5Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CN8EEYklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CN8EEIklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CN8EEoklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_pZQAsIsMEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pZQAsYsMEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qK8jYIsMEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pZQAsosMEeqHHvcBOa57dw" name="status" content="status" type="TYPE_CONTRACT_INPUT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_uvEO0IsMEeqHHvcBOa57dw" name="status" description="Estado da validação da despesa">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_uvEO0YsMEeqHHvcBOa57dw"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pZQAs4sMEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_vglLUIsMEeqHHvcBOa57dw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_vglLUYsMEeqHHvcBOa57dw" name="compraPedido" content="compraPedido" type="TYPE_VARIABLE" returnType="com.company.model.comprasPedidos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_v1BxUIsMEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_vglLUosMEeqHHvcBOa57dw" name="motivoDeRecusa" content="motivoDeRecusa" type="TYPE_CONTRACT_INPUT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xa2foIsMEeqHHvcBOa57dw" name="motivoDeRecusa" description="Se a despesa for recusada, tem que ser dada uma razão">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_xa2foYsMEeqHHvcBOa57dw"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_vglLU4sMEeqHHvcBOa57dw" type="JAVA_METHOD" expression="setMotivoRecusa">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_CN8EE4klEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_CN8EFIklEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_CN8EFYklEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_CN8EF4klEeqCs6_Zt3VV5Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_CN8EFoklEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_J6bUSYsKEeqHHvcBOa57dw">
            <targetForm xmi:type="expression:Expression" xmi:id="_QuxV4IsKEeqHHvcBOa57dw" name="newForm" content="6f4486ec-cfa5-40b2-bb16-1a93b82cfba6" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_J6bUSIsKEeqHHvcBOa57dw">
            <inputs xmi:type="process:ContractInput" xmi:id="_LE9i0IsMEeqHHvcBOa57dw" name="status" description="Estado da validação da despesa">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_LE9i0YsMEeqHHvcBOa57dw"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_NDd24IsMEeqHHvcBOa57dw" name="motivoDeRecusa" description="Se a despesa for recusada, tem que ser dada uma razão">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_NDd24YsMEeqHHvcBOa57dw"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_RTeTgIsMEeqHHvcBOa57dw" expression="status == &quot;aprovado&quot; || (status == &quot;recusado&quot; &amp;&amp; motivoDeRecusa?.trim())&#xD;&#xA;return true;" errorMessage="Se a despesa for recusada, tem que existir uam razão" name="razaoObrigatoria">
              <inputNames>motivoDeRecusa</inputNames>
              <inputNames>status</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_J6bUS4sKEeqHHvcBOa57dw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="__vl4IIPbEeqXlKUduLqENg" name="UJC">
        <elements xmi:type="process:ServiceTask" xmi:id="_-uXwcIklEeqCs6_Zt3VV5Q" name="Validar informação" outgoing="_IW0b8IknEeqCs6_Zt3VV5Q" incoming="_ES2FoIkmEeqCs6_Zt3VV5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-uXwcoklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-uXwcYklEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-uXwc4klEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-uXwdIklEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-uXwdYklEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-uXwdoklEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-uXweIklEeqCs6_Zt3VV5Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-uXwd4klEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ZHhOcIkmEeqCs6_Zt3VV5Q" name="Dados Válidos?" outgoing="_KGseIIknEeqCs6_Zt3VV5Q _NX-MMIkoEeqCs6_Zt3VV5Q" incoming="_IW0b8IknEeqCs6_Zt3VV5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZHh1gYkmEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZHh1gIkmEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZHh1gokmEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_B08bEIPcEeqXlKUduLqENg" name="UCF">
        <elements xmi:type="process:ServiceTask" xmi:id="_sw_6AIknEeqCs6_Zt3VV5Q" name="Validar informação" outgoing="_K5rIUIkpEeqCs6_Zt3VV5Q" incoming="_KGseIIknEeqCs6_Zt3VV5Q _Wi_KQIkoEeqCs6_Zt3VV5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sw_6AoknEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sw_6AYknEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sw_6A4knEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_sw_6BIknEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_sw_6BYknEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_sw_6BoknEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_sw_6CIknEeqCs6_Zt3VV5Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_sw_6B4knEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_daGMAIkoEeqCs6_Zt3VV5Q" name="Dados validados?" outgoing="_YLsYAIkpEeqCs6_Zt3VV5Q _GKBF0IkqEeqCs6_Zt3VV5Q" incoming="_K5rIUIkpEeqCs6_Zt3VV5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_daGzEYkoEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_daGzEIkoEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_daGzEokoEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_P3Y_gIkpEeqCs6_Zt3VV5Q" outgoing="_eauGEIkpEeqCs6_Zt3VV5Q" incoming="_0O2qgIlaEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_P3ZmkYkpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_P3ZmkIkpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_P3ZmkokpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_UuLvUIkpEeqCs6_Zt3VV5Q" name="Verificar cabimento" outgoing="_OWyS8IkqEeqCs6_Zt3VV5Q" incoming="_YLsYAIkpEeqCs6_Zt3VV5Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_T67tcokpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_T67tcYkpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_T67tc4kpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_T67tdIkpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_T67tdYkpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_T67tdokpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_T68UgYkpEeqCs6_Zt3VV5Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_T68UgIkpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_UuMWaYkpEeqCs6_Zt3VV5Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_UuMWaokpEeqCs6_Zt3VV5Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_UuMWaIkpEeqCs6_Zt3VV5Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_UuMWa4kpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_qA9wcIkpEeqCs6_Zt3VV5Q" name="Há cabimento?" outgoing="_iZX3gIkqEeqCs6_Zt3VV5Q _0O2qgIlaEeqm0fYUL6Uqjg" incoming="_OWyS8IkqEeqCs6_Zt3VV5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qA-XgYkpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qA-XgIkpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qA-XgokpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_hokssIkqEeqCs6_Zt3VV5Q" name="Criar número de cabimento" outgoing="_vnLVkIkqEeqCs6_Zt3VV5Q" incoming="_iZX3gIkqEeqCs6_Zt3VV5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z-288okpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z-288YkpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z-2884kpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_z-3kAIkpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_z-3kAYkpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_z-3kAokpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_z-3kBIkpEeqCs6_Zt3VV5Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_z-3kA4kpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_nZ5LEIkqEeqCs6_Zt3VV5Q" name="&lt;=1500€" outgoing="_uhk7cIlWEeqm0fYUL6Uqjg _aW2jAIlgEeqm0fYUL6Uqjg" incoming="_vnLVkIkqEeqCs6_Zt3VV5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nZ5yIYkqEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nZ5yIIkqEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nZ5yIokqEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_owWnsIkqEeqCs6_Zt3VV5Q" name="> 1500€ &lt;=5000€" outgoing="_wSpE4IlgEeqm0fYUL6Uqjg" incoming="_aW2jAIlgEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_owWnsokqEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_owWnsYkqEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_owWns4kqEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_NmgkoIPcEeqXlKUduLqENg" name="Gestor de Projeto / Responsável da Unidade Validador da despesa">
        <elements xmi:type="process:ServiceTask" xmi:id="_nQK_0IlVEeqm0fYUL6Uqjg" name="Validar informação" outgoing="_K08qcIlXEeqm0fYUL6Uqjg" incoming="_uhk7cIlWEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yWAIwokpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yWAIwYkpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yWAIw4kpEeqCs6_Zt3VV5Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yWAIxIkpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yWAIxYkpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yWAIxokpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yWAIyIkpEeqCs6_Zt3VV5Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yWAIx4kpEeqCs6_Zt3VV5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_8dmxcIlWEeqm0fYUL6Uqjg" name="Informação válida?" outgoing="_NpB7oIlXEeqm0fYUL6Uqjg _AWcZUIlZEeqm0fYUL6Uqjg" incoming="_K08qcIlXEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8dmxcolWEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8dmxcYlWEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8dmxc4lWEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_MwE6YIlXEeqm0fYUL6Uqjg" outgoing="_N89HwIlYEeqm0fYUL6Uqjg" incoming="_NpB7oIlXEeqm0fYUL6Uqjg _Vya5EIlhEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MwFhcYlXEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MwFhcIlXEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MwFhcolXEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_-pST8IlYEeqm0fYUL6Uqjg" outgoing="_n2KLUIlhEeqm0fYUL6Uqjg _-DoTEIlhEeqm0fYUL6Uqjg" incoming="_AWcZUIlZEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-pS7AYlYEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-pS7AIlYEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-pS7AolYEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_it7U8IlbEeqm0fYUL6Uqjg" name="Anular Cabimento" outgoing="_pplfgIlbEeqm0fYUL6Uqjg" incoming="__MVnkIlhEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f8GGgolbEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f8GGgYlbEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f8GGg4lbEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_f8GGhIlbEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_f8GGhYlbEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_f8GGholbEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_f8GGiIlbEeqm0fYUL6Uqjg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_f8GGh4lbEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_l0QMsIlbEeqm0fYUL6Uqjg" name="Compra anulada" incoming="_pplfgIlbEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_l0QzwIlbEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_l0QMsYlbEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_l0QzwYlbEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_LQ6mQIPcEeqXlKUduLqENg" name="Diretor da Área Validador da despesa">
        <elements xmi:type="process:ServiceTask" xmi:id="_l5A-oIlgEeqm0fYUL6Uqjg" name="Validar informação" outgoing="_sB_IAIlgEeqm0fYUL6Uqjg" incoming="_wSpE4IlgEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fpHt4IlgEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fpHG0YlgEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fpHt4YlgEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_fpHt4olgEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_fpHt44lgEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_fpHt5IlgEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_fpHt5olgEeqm0fYUL6Uqjg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_fpHt5YlgEeqm0fYUL6Uqjg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ojBt0IlgEeqm0fYUL6Uqjg" name="Informação válida?" outgoing="_JII-0IlhEeqm0fYUL6Uqjg _Vya5EIlhEeqm0fYUL6Uqjg" incoming="_sB_IAIlgEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ojBt0olgEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ojBt0YlgEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ojBt04lgEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_EwxV8IlhEeqm0fYUL6Uqjg" outgoing="_p9cn8IlhEeqm0fYUL6Uqjg _-qCLwIlhEeqm0fYUL6Uqjg" incoming="_JII-0IlhEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ewx9AYlhEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ewx9AIlhEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ewx9AolhEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_8lVJEIlhEeqm0fYUL6Uqjg" outgoing="__MVnkIlhEeqm0fYUL6Uqjg" incoming="_-DoTEIlhEeqm0fYUL6Uqjg _-qCLwIlhEeqm0fYUL6Uqjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8lVwIYlhEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8lVwIIlhEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8lVwIolhEeqm0fYUL6Uqjg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_TiodMIlgEeqm0fYUL6Uqjg" name="CA"/>
      <data xmi:type="process:BusinessObjectData" xmi:id="_-vNvIIsAEeqHHvcBOa57dw" documentation="Pedido para pagamento de um compra" name="compraPedido" dataType="_j8C45IPbEeqXlKUduLqENg" className="com.company.model.comprasPedidos">
        <defaultValue xmi:type="expression:Expression" xmi:id="_4X1g4IsBEeqHHvcBOa57dw" name="initCompraPedido()" content="def comprasPedidosVar = new com.company.model.comprasPedidos()&#xD;&#xA;comprasPedidosVar.compraID = BonitaUsers.getProcessInstanceInitiator(apiAccessor, processInstanceId).id&#xD;&#xA;comprasPedidosVar.status = &quot;pendente&quot; &#xD;&#xA;comprasPedidosVar.dataCompra =      ?.dataCompra&#xD;&#xA;comprasPedidosVar.nomeCompra =      ?.nomeCompra&#xD;&#xA;comprasPedidosVar.numCompromisso =      ?.numCompromisso?.trim() ?      .numCompromisso.toLong() : null&#xD;&#xA;comprasPedidosVar.temCabimento =      ?.temCabimento&#xD;&#xA;comprasPedidosVar.numCabimento =      ?.numCabimento?.trim() ?      .numCabimento.toLong() : null&#xD;&#xA;comprasPedidosVar.valorCompra =      ?.valorCompra?.toFloat()&#xD;&#xA;return comprasPedidosVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.comprasPedidos">
          <referencedElements xmi:type="expression:Expression" xmi:id="_gx3DMIsDEeqHHvcBOa57dw" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
          <referencedElements xmi:type="expression:Expression" xmi:id="_gx3DMosDEeqHHvcBOa57dw" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_j8C4xIPbEeqXlKUduLqENg">
        <targetForm xmi:type="expression:Expression" xmi:id="_j8C4xYPbEeqXlKUduLqENg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_j8C4xoPbEeqXlKUduLqENg">
        <targetForm xmi:type="expression:Expression" xmi:id="__tsP8IsIEeqHHvcBOa57dw" name="submitPedidoCompra" content="b597202f-9aaf-40d9-9a83-ea0b5376891c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jlBDUIPcEeqXlKUduLqENg" target="_g_6CQIPcEeqXlKUduLqENg" source="_j8C4s4PbEeqXlKUduLqENg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jlBDUYPcEeqXlKUduLqENg"/>
        <condition xmi:type="expression:Expression" xmi:id="_jlBDUoPcEeqXlKUduLqENg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x1en4IkkEeqCs6_Zt3VV5Q" target="_j8C4t4PbEeqXlKUduLqENg" source="_g_6CQIPcEeqXlKUduLqENg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x1oY4IkkEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_x1o_8IkkEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gp7scIklEeqCs6_Zt3VV5Q" target="_J6atMIsKEeqHHvcBOa57dw" source="_j8C4t4PbEeqXlKUduLqENg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gp7scYklEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_gp7scoklEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jLzzUIklEeqCs6_Zt3VV5Q" name="Não" target="_GjV-EIklEeqCs6_Zt3VV5Q" source="_GMGiwIklEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jLzzUYklEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_jL0aYIklEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_k00YgIklEeqCs6_Zt3VV5Q" target="_g_6CQIPcEeqXlKUduLqENg" source="_GjV-EIklEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_k00YgYklEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_k00YgoklEeqCs6_Zt3VV5Q" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wNhWIIklEeqCs6_Zt3VV5Q" target="_ruQ8kIklEeqCs6_Zt3VV5Q" source="_GjV-EIklEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wNh9MIklEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_wNh9MYklEeqCs6_Zt3VV5Q" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yH7NUIklEeqCs6_Zt3VV5Q" target="_GMGiwIklEeqCs6_Zt3VV5Q" source="_J6atMIsKEeqHHvcBOa57dw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yH7NUYklEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_yH7NUoklEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ES2FoIkmEeqCs6_Zt3VV5Q" name="Sim" target="_-uXwcIklEeqCs6_Zt3VV5Q" source="_GMGiwIklEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ES2ssIkmEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_ES2ssYkmEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IW0b8IknEeqCs6_Zt3VV5Q" target="_ZHhOcIkmEeqCs6_Zt3VV5Q" source="_-uXwcIklEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IW0b8YknEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_IW0b8oknEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KGseIIknEeqCs6_Zt3VV5Q" documentation="&#xD;&#xA;" name="Sim" target="_sw_6AIknEeqCs6_Zt3VV5Q" source="_ZHhOcIkmEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KGseIYknEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_KGseIoknEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NX-MMIkoEeqCs6_Zt3VV5Q" name="Não" target="_g_6CQIPcEeqXlKUduLqENg" source="_ZHhOcIkmEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NX-MMYkoEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_NX-zQIkoEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Wi_KQIkoEeqCs6_Zt3VV5Q" target="_sw_6AIknEeqCs6_Zt3VV5Q" source="__tHGEIkkEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Wi_KQYkoEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Wi_KQokoEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_K5rIUIkpEeqCs6_Zt3VV5Q" name="Dados Válidos?" target="_daGMAIkoEeqCs6_Zt3VV5Q" source="_sw_6AIknEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_K5rvYIkpEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_K5rvYYkpEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YLsYAIkpEeqCs6_Zt3VV5Q" target="_UuLvUIkpEeqCs6_Zt3VV5Q" source="_daGMAIkoEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YLsYAYkpEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_YLsYAokpEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_eauGEIkpEeqCs6_Zt3VV5Q" target="__tHGEIkkEeqCs6_Zt3VV5Q" source="_P3Y_gIkpEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_eauGEYkpEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_eautIIkpEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GKBF0IkqEeqCs6_Zt3VV5Q" name="Não" target="_g_6CQIPcEeqXlKUduLqENg" source="_daGMAIkoEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GKBs4IkqEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_GKBs4YkqEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OWyS8IkqEeqCs6_Zt3VV5Q" target="_qA9wcIkpEeqCs6_Zt3VV5Q" source="_UuLvUIkpEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OWyS8YkqEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_OWyS8okqEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iZX3gIkqEeqCs6_Zt3VV5Q" name="Sim" target="_hokssIkqEeqCs6_Zt3VV5Q" source="_qA9wcIkpEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iZX3gYkqEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_iZX3gokqEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vnLVkIkqEeqCs6_Zt3VV5Q" target="_nZ5LEIkqEeqCs6_Zt3VV5Q" source="_hokssIkqEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vnLVkYkqEeqCs6_Zt3VV5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_vnLVkokqEeqCs6_Zt3VV5Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uhk7cIlWEeqm0fYUL6Uqjg" target="_nQK_0IlVEeqm0fYUL6Uqjg" source="_nZ5LEIkqEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uhligIlWEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_uhligYlWEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_K08qcIlXEeqm0fYUL6Uqjg" target="_8dmxcIlWEeqm0fYUL6Uqjg" source="_nQK_0IlVEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_K09RgIlXEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_K09RgYlXEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NpB7oIlXEeqm0fYUL6Uqjg" name="Sim" target="_MwE6YIlXEeqm0fYUL6Uqjg" source="_8dmxcIlWEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NpB7oYlXEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_NpB7oolXEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_N89HwIlYEeqm0fYUL6Uqjg" target="_GE4YQIlYEeqm0fYUL6Uqjg" source="_MwE6YIlXEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_N89HwYlYEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_N89HwolYEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_W_ffQIlYEeqm0fYUL6Uqjg" target="_TGM5gIlYEeqm0fYUL6Uqjg" source="_GE4YQIlYEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_W_ffQYlYEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_W_ffQolYEeqm0fYUL6Uqjg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AWcZUIlZEeqm0fYUL6Uqjg" name="Não" target="_-pST8IlYEeqm0fYUL6Uqjg" source="_8dmxcIlWEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AWdAYIlZEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_AWdAYYlZEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0O2qgIlaEeqm0fYUL6Uqjg" name="Não" target="_P3Y_gIkpEeqCs6_Zt3VV5Q" source="_qA9wcIkpEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0O2qgYlaEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_0O2qgolaEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pplfgIlbEeqm0fYUL6Uqjg" target="_l0QMsIlbEeqm0fYUL6Uqjg" source="_it7U8IlbEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pplfgYlbEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_pplfgolbEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aW2jAIlgEeqm0fYUL6Uqjg" target="_owWnsIkqEeqCs6_Zt3VV5Q" source="_nZ5LEIkqEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aW3KEIlgEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_aW3KEYlgEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sB_IAIlgEeqm0fYUL6Uqjg" target="_ojBt0IlgEeqm0fYUL6Uqjg" source="_l5A-oIlgEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sB_vEIlgEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_sB_vEYlgEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wSpE4IlgEeqm0fYUL6Uqjg" target="_l5A-oIlgEeqm0fYUL6Uqjg" source="_owWnsIkqEeqCs6_Zt3VV5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wSpE4YlgEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_wSpE4olgEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JII-0IlhEeqm0fYUL6Uqjg" target="_EwxV8IlhEeqm0fYUL6Uqjg" source="_ojBt0IlgEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JII-0YlhEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_JII-0olhEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Vya5EIlhEeqm0fYUL6Uqjg" name="Sim" target="_MwE6YIlXEeqm0fYUL6Uqjg" source="_ojBt0IlgEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Vya5EYlhEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Vya5EolhEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_n2KLUIlhEeqm0fYUL6Uqjg" target="_g_6CQIPcEeqXlKUduLqENg" source="_-pST8IlYEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_n2KLUYlhEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_n2KLUolhEeqm0fYUL6Uqjg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_p9cn8IlhEeqm0fYUL6Uqjg" target="_g_6CQIPcEeqXlKUduLqENg" source="_EwxV8IlhEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_p9cn8YlhEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_p9cn8olhEeqm0fYUL6Uqjg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-DoTEIlhEeqm0fYUL6Uqjg" target="_8lVJEIlhEeqm0fYUL6Uqjg" source="_-pST8IlYEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-DoTEYlhEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_-DoTEolhEeqm0fYUL6Uqjg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-qCLwIlhEeqm0fYUL6Uqjg" target="_8lVJEIlhEeqm0fYUL6Uqjg" source="_EwxV8IlhEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-qCLwYlhEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_-qCLwolhEeqm0fYUL6Uqjg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__MVnkIlhEeqm0fYUL6Uqjg" target="_it7U8IlbEeqm0fYUL6Uqjg" source="_8lVJEIlhEeqm0fYUL6Uqjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__MVnkYlhEeqm0fYUL6Uqjg"/>
        <condition xmi:type="expression:Expression" xmi:id="__MVnkolhEeqm0fYUL6Uqjg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_j8C4y4PbEeqXlKUduLqENg" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_j8C4zIPbEeqXlKUduLqENg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_j8C4zYPbEeqXlKUduLqENg">
        <name xmi:type="expression:Expression" xmi:id="_j8C4zoPbEeqXlKUduLqENg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_j8C4z4PbEeqXlKUduLqENg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_j8C40IPbEeqXlKUduLqENg">
        <name xmi:type="expression:Expression" xmi:id="_j8C40YPbEeqXlKUduLqENg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_j8C40oPbEeqXlKUduLqENg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_j8C404PbEeqXlKUduLqENg">
        <name xmi:type="expression:Expression" xmi:id="_j8C41IPbEeqXlKUduLqENg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_j8C41YPbEeqXlKUduLqENg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_j8C41oPbEeqXlKUduLqENg">
        <name xmi:type="expression:Expression" xmi:id="_j8C414PbEeqXlKUduLqENg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_j8C42IPbEeqXlKUduLqENg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_j8C42YPbEeqXlKUduLqENg">
        <name xmi:type="expression:Expression" xmi:id="_j8C42oPbEeqXlKUduLqENg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_j8C424PbEeqXlKUduLqENg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_j8C43IPbEeqXlKUduLqENg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_j8C43YPbEeqXlKUduLqENg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_j8C43oPbEeqXlKUduLqENg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_j8C434PbEeqXlKUduLqENg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_j8C44IPbEeqXlKUduLqENg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_j8C44YPbEeqXlKUduLqENg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_j8C44oPbEeqXlKUduLqENg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_j8C444PbEeqXlKUduLqENg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_j8C45IPbEeqXlKUduLqENg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_j8C45YPbEeqXlKUduLqENg" type="Process" element="_j8C4sIPbEeqXlKUduLqENg" name="MyDiagram1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_j8C45oPbEeqXlKUduLqENg" type="2007" element="_j8C4sYPbEeqXlKUduLqENg">
      <children xmi:type="notation:DecorationNode" xmi:id="_j8C454PbEeqXlKUduLqENg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_j8C46IPbEeqXlKUduLqENg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_j8C46YPbEeqXlKUduLqENg" type="3007" element="_j8C4soPbEeqXlKUduLqENg">
          <children xmi:type="notation:DecorationNode" xmi:id="_j8C46oPbEeqXlKUduLqENg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_j8C464PbEeqXlKUduLqENg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_j8C47IPbEeqXlKUduLqENg" type="3005" element="_j8C4t4PbEeqXlKUduLqENg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_j8C47YPbEeqXlKUduLqENg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_j8C47oPbEeqXlKUduLqENg" x="446" y="95"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_j8C474PbEeqXlKUduLqENg" type="3002" element="_j8C4s4PbEeqXlKUduLqENg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_j8C48IPbEeqXlKUduLqENg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_j8C48YPbEeqXlKUduLqENg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_j8C48oPbEeqXlKUduLqENg" x="99" y="205"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_g_6pUIPcEeqXlKUduLqENg" type="3008" element="_g_6CQIPcEeqXlKUduLqENg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_g_6pUoPcEeqXlKUduLqENg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_g_6pU4PcEeqXlKUduLqENg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g_6pUYPcEeqXlKUduLqENg" x="251" y="198"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GE4_UIlYEeqm0fYUL6Uqjg" type="3027" element="_GE4YQIlYEeqm0fYUL6Uqjg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GE4_UolYEeqm0fYUL6Uqjg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GE4_UYlYEeqm0fYUL6Uqjg" x="1676" y="255" width="168" height="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TGOHoIlYEeqm0fYUL6Uqjg" type="3003" element="_TGM5gIlYEeqm0fYUL6Uqjg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_TGOusIlYEeqm0fYUL6Uqjg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TGOusYlYEeqm0fYUL6Uqjg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TGOHoYlYEeqm0fYUL6Uqjg" x="1942" y="284"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_j8C484PbEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_j8C49IPbEeqXlKUduLqENg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_j8C49YPbEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_j8C49oPbEeqXlKUduLqENg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_j8C494PbEeqXlKUduLqENg" x="48" y="10" width="927" height="400"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_6nRTcIPbEeqXlKUduLqENg" type="3007" element="_6nQsYIPbEeqXlKUduLqENg">
          <children xmi:type="notation:DecorationNode" xmi:id="_6nRTdYPbEeqXlKUduLqENg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_6nRTdoPbEeqXlKUduLqENg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="__tJiUIkkEeqCs6_Zt3VV5Q" type="3005" element="__tHGEIkkEeqCs6_Zt3VV5Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__tKJYIkkEeqCs6_Zt3VV5Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__tJiUYkkEeqCs6_Zt3VV5Q" x="80" y="170"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GMIX8IklEeqCs6_Zt3VV5Q" type="3008" element="_GMGiwIklEeqCs6_Zt3VV5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_GMIX8oklEeqCs6_Zt3VV5Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_GMIX84klEeqCs6_Zt3VV5Q" x="1" y="-70"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GMIX8YklEeqCs6_Zt3VV5Q" x="536" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GjXMMIklEeqCs6_Zt3VV5Q" type="3009" element="_GjV-EIklEeqCs6_Zt3VV5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_GjXMMoklEeqCs6_Zt3VV5Q" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_GjXMM4klEeqCs6_Zt3VV5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GjXMMYklEeqCs6_Zt3VV5Q" x="536" y="170"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ruSKsIklEeqCs6_Zt3VV5Q" type="3027" element="_ruQ8kIklEeqCs6_Zt3VV5Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ruSKsoklEeqCs6_Zt3VV5Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ruSKsYklEeqCs6_Zt3VV5Q" x="509" y="303"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_J6bUTIsKEeqHHvcBOa57dw" type="3005" element="_J6atMIsKEeqHHvcBOa57dw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_J6b7UIsKEeqHHvcBOa57dw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_J6bUTYsKEeqHHvcBOa57dw" x="345" y="56" width="100" height="49"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_6nRTcYPbEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_6nRTcoPbEeqXlKUduLqENg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_6nRTc4PbEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_6nRTd4PbEeqXlKUduLqENg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6nRTdIPbEeqXlKUduLqENg" x="48" y="400" width="927" height="452"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="__vmfMIPbEeqXlKUduLqENg" type="3007" element="__vl4IIPbEeqXlKUduLqENg">
          <children xmi:type="notation:DecorationNode" xmi:id="__vmfNYPbEeqXlKUduLqENg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="__vmfNoPbEeqXlKUduLqENg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_-uY-kIklEeqCs6_Zt3VV5Q" type="3027" element="_-uXwcIklEeqCs6_Zt3VV5Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-uY-koklEeqCs6_Zt3VV5Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-uY-kYklEeqCs6_Zt3VV5Q" x="669" y="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZHh1g4kmEeqCs6_Zt3VV5Q" type="3008" element="_ZHhOcIkmEeqCs6_Zt3VV5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZHickIkmEeqCs6_Zt3VV5Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZHickYkmEeqCs6_Zt3VV5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZHh1hIkmEeqCs6_Zt3VV5Q" x="688" y="150"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="__vmfMYPbEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="__vmfMoPbEeqXlKUduLqENg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="__vmfM4PbEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="__vmfN4PbEeqXlKUduLqENg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="__vmfNIPbEeqXlKUduLqENg" x="48" y="852" width="927" height="344"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_B09CIIPcEeqXlKUduLqENg" type="3007" element="_B08bEIPcEeqXlKUduLqENg">
          <children xmi:type="notation:DecorationNode" xmi:id="_B09CJYPcEeqXlKUduLqENg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_B09CJoPcEeqXlKUduLqENg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_sxAhEIknEeqCs6_Zt3VV5Q" type="3027" element="_sw_6AIknEeqCs6_Zt3VV5Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_sxAhEoknEeqCs6_Zt3VV5Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sxAhEYknEeqCs6_Zt3VV5Q" x="659" y="28"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_daGzE4koEeqCs6_Zt3VV5Q" type="3008" element="_daGMAIkoEeqCs6_Zt3VV5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_daGzFYkoEeqCs6_Zt3VV5Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_daGzFokoEeqCs6_Zt3VV5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_daGzFIkoEeqCs6_Zt3VV5Q" x="687" y="276"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_P3Zmk4kpEeqCs6_Zt3VV5Q" type="3008" element="_P3Y_gIkpEeqCs6_Zt3VV5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_P3aNoIkpEeqCs6_Zt3VV5Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_P3aNoYkpEeqCs6_Zt3VV5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P3ZmlIkpEeqCs6_Zt3VV5Q" x="108" y="381"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UuM9cIkpEeqCs6_Zt3VV5Q" type="3005" element="_UuLvUIkpEeqCs6_Zt3VV5Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_UuM9cokpEeqCs6_Zt3VV5Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UuM9cYkpEeqCs6_Zt3VV5Q" x="1003" y="283" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qA-Xg4kpEeqCs6_Zt3VV5Q" type="3008" element="_qA9wcIkpEeqCs6_Zt3VV5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qA-XhYkpEeqCs6_Zt3VV5Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qA-XhokpEeqCs6_Zt3VV5Q" x="57" y="-5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qA-XhIkpEeqCs6_Zt3VV5Q" x="1022" y="378"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hoksuYkqEeqCs6_Zt3VV5Q" type="3027" element="_hokssIkqEeqCs6_Zt3VV5Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_holTwIkqEeqCs6_Zt3VV5Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hoksuokqEeqCs6_Zt3VV5Q" x="983" y="502" width="140" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nZ6ZMIkqEeqCs6_Zt3VV5Q" type="3008" element="_nZ5LEIkqEeqCs6_Zt3VV5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_nZ6ZMokqEeqCs6_Zt3VV5Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_nZ6ZM4kqEeqCs6_Zt3VV5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nZ6ZMYkqEeqCs6_Zt3VV5Q" x="1274" y="502"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_owXOwIkqEeqCs6_Zt3VV5Q" type="3008" element="_owWnsIkqEeqCs6_Zt3VV5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_owXOwokqEeqCs6_Zt3VV5Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_owXOw4kqEeqCs6_Zt3VV5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_owXOwYkqEeqCs6_Zt3VV5Q" x="1535" y="495"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_B09CIYPcEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_B09CIoPcEeqXlKUduLqENg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_B09CI4PcEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_B09CJ4PcEeqXlKUduLqENg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_B09CJIPcEeqXlKUduLqENg" x="48" y="1196" width="1977" height="656"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_LQ7NUIPcEeqXlKUduLqENg" type="3007" element="_LQ6mQIPcEeqXlKUduLqENg">
          <children xmi:type="notation:DecorationNode" xmi:id="_LQ7NVYPcEeqXlKUduLqENg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_LQ7NVoPcEeqXlKUduLqENg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_l5BluIlgEeqm0fYUL6Uqjg" type="3027" element="_l5A-oIlgEeqm0fYUL6Uqjg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_l5BluolgEeqm0fYUL6Uqjg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l5BluYlgEeqm0fYUL6Uqjg" x="1516" y="34" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ojCU4IlgEeqm0fYUL6Uqjg" type="3008" element="_ojBt0IlgEeqm0fYUL6Uqjg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ojCU4olgEeqm0fYUL6Uqjg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ojCU44lgEeqm0fYUL6Uqjg" x="-14" y="11"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ojCU4YlgEeqm0fYUL6Uqjg" x="1535" y="129"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EwykEIlhEeqm0fYUL6Uqjg" type="3009" element="_EwxV8IlhEeqm0fYUL6Uqjg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_EwykEolhEeqm0fYUL6Uqjg" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_EwykE4lhEeqm0fYUL6Uqjg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EwykEYlhEeqm0fYUL6Uqjg" x="1535" y="224"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8lVwI4lhEeqm0fYUL6Uqjg" type="3008" element="_8lVJEIlhEeqm0fYUL6Uqjg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8lVwJYlhEeqm0fYUL6Uqjg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8lVwJolhEeqm0fYUL6Uqjg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8lVwJIlhEeqm0fYUL6Uqjg" x="1930" y="110"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_LQ7NUYPcEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_LQ7NUoPcEeqXlKUduLqENg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_LQ7NU4PcEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_LQ7NV4PcEeqXlKUduLqENg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LQ7NVIPcEeqXlKUduLqENg" x="48" y="2227" width="2147" height="322"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_NmgkoYPcEeqXlKUduLqENg" type="3007" element="_NmgkoIPcEeqXlKUduLqENg">
          <children xmi:type="notation:DecorationNode" xmi:id="_NmhLsIPcEeqXlKUduLqENg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_NmhLsYPcEeqXlKUduLqENg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_nQnEsIlVEeqm0fYUL6Uqjg" type="3027" element="_nQK_0IlVEeqm0fYUL6Uqjg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nQoS0IlVEeqm0fYUL6Uqjg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nQnEsYlVEeqm0fYUL6Uqjg" x="1221" y="37" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8dnYgIlWEeqm0fYUL6Uqjg" type="3008" element="_8dmxcIlWEeqm0fYUL6Uqjg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8dnYgolWEeqm0fYUL6Uqjg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8dn_kIlWEeqm0fYUL6Uqjg" y="2"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8dnYgYlWEeqm0fYUL6Uqjg" x="1269" y="143"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_MwGIgIlXEeqm0fYUL6Uqjg" type="3008" element="_MwE6YIlXEeqm0fYUL6Uqjg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_MwGIgolXEeqm0fYUL6Uqjg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_MwGIg4lXEeqm0fYUL6Uqjg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MwGIgYlXEeqm0fYUL6Uqjg" x="1763" y="160"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-pTiEIlYEeqm0fYUL6Uqjg" type="3009" element="_-pST8IlYEeqm0fYUL6Uqjg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_-pTiEolYEeqm0fYUL6Uqjg" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_-pTiE4lYEeqm0fYUL6Uqjg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-pTiEYlYEeqm0fYUL6Uqjg" x="1269" y="256"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_it78CIlbEeqm0fYUL6Uqjg" type="3027" element="_it7U8IlbEeqm0fYUL6Uqjg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_it8jEIlbEeqm0fYUL6Uqjg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_it78CYlbEeqm0fYUL6Uqjg" x="1873" y="219" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_l0QzwolbEeqm0fYUL6Uqjg" type="3003" element="_l0QMsIlbEeqm0fYUL6Uqjg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_l0QzxIlbEeqm0fYUL6Uqjg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_l0QzxYlbEeqm0fYUL6Uqjg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l0Qzw4lbEeqm0fYUL6Uqjg" x="2048" y="218"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_NmgkooPcEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Nmgko4PcEeqXlKUduLqENg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_NmgkpIPcEeqXlKUduLqENg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_NmhLsoPcEeqXlKUduLqENg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NmgkpYPcEeqXlKUduLqENg" x="48" y="1852" width="2147" height="375"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_TiprUIlgEeqm0fYUL6Uqjg" type="3007" element="_TiodMIlgEeqm0fYUL6Uqjg">
          <children xmi:type="notation:DecorationNode" xmi:id="_TiprVYlgEeqm0fYUL6Uqjg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_TiprVolgEeqm0fYUL6Uqjg" type="7002"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_TiprUYlgEeqm0fYUL6Uqjg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_TiprUolgEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_TiprU4lgEeqm0fYUL6Uqjg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_TiprV4lgEeqm0fYUL6Uqjg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TiprVIlgEeqm0fYUL6Uqjg" x="198" y="2362"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_j8C4-IPbEeqXlKUduLqENg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_j8C4-YPbEeqXlKUduLqENg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_j8C4-oPbEeqXlKUduLqENg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_j8C4-4PbEeqXlKUduLqENg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_j8C4_IPbEeqXlKUduLqENg" width="2170" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_j8C4_YPbEeqXlKUduLqENg"/>
    <edges xmi:type="notation:Connector" xmi:id="_jlBDU4PcEeqXlKUduLqENg" type="4001" element="_jlBDUIPcEeqXlKUduLqENg" source="_j8C474PbEeqXlKUduLqENg" target="_g_6pUIPcEeqXlKUduLqENg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jlBqYIPcEeqXlKUduLqENg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jlBqYYPcEeqXlKUduLqENg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jlBDVIPcEeqXlKUduLqENg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jlBDVYPcEeqXlKUduLqENg" points="[12, 8, -146, 9]$[71, 8, -87, 9]$[71, 4, -87, 5]$[141, 4, -17, 5]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x2OOwIkkEeqCs6_Zt3VV5Q" type="4001" element="_x1en4IkkEeqCs6_Zt3VV5Q" source="_g_6pUIPcEeqXlKUduLqENg" target="_j8C47IPbEeqXlKUduLqENg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x2Pc4IkkEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x2Pc4YkkEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x2OOwYkkEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x2OOwokkEeqCs6_Zt3VV5Q" points="[-23, -37, -185, 77]$[-23, -109, -185, 5]$[152, -109, -10, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x2U8cIkkEeqCs6_Zt3VV5Q" id="(1.0,0.8837209302325582)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x2U8cYkkEeqCs6_Zt3VV5Q" id="(0.1,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gp86kIklEeqCs6_Zt3VV5Q" type="4001" element="_gp7scIklEeqCs6_Zt3VV5Q" source="_j8C47IPbEeqXlKUduLqENg" target="_J6bUTIsKEeqHHvcBOa57dw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gp86k4klEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gp9hoIklEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gp86kYklEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gp86koklEeqCs6_Zt3VV5Q" points="[-2, 13, 18, -184]$[-21, 200, -1, 3]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gp_94IklEeqCs6_Zt3VV5Q" id="(0.48,0.88)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jMCc0IklEeqCs6_Zt3VV5Q" type="4001" element="_jLzzUIklEeqCs6_Zt3VV5Q" source="_GMIX8IklEeqCs6_Zt3VV5Q" target="_GjXMMIklEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jMDD4IklEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jMDD4YklEeqCs6_Zt3VV5Q" x="10" y="-28"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jMCc0YklEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jMCc0oklEeqCs6_Zt3VV5Q" points="[0, 22, 0, -88]$[0, 89, 0, -21]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_k00_kIklEeqCs6_Zt3VV5Q" type="4001" element="_k00YgIklEeqCs6_Zt3VV5Q" source="_GjXMMIklEeqCs6_Zt3VV5Q" target="_g_6pUIPcEeqXlKUduLqENg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_k00_k4klEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_k00_lIklEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_k00_kYklEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_k00_koklEeqCs6_Zt3VV5Q" points="[-4, 12, 264, 373]$[-243, 12, 25, 373]$[-243, -361, 25, 0]$[-246, -361, 22, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_k03b0IklEeqCs6_Zt3VV5Q" id="(0.09302325581395349,0.23255813953488372)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wNikQIklEeqCs6_Zt3VV5Q" type="4001" element="_wNhWIIklEeqCs6_Zt3VV5Q" source="_GjXMMIklEeqCs6_Zt3VV5Q" target="_ruSKsIklEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wNjLUIklEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wNjLUYklEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wNikQYklEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wNikQoklEeqCs6_Zt3VV5Q" points="[-4, 17, 25, -125]$[-4, 69, 25, -73]$[0, 69, 29, -73]$[0, 120, 29, -22]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wNlAgIklEeqCs6_Zt3VV5Q" id="(0.19,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yH70YIklEeqCs6_Zt3VV5Q" type="4001" element="_yH7NUIklEeqCs6_Zt3VV5Q" source="_J6bUTIsKEeqHHvcBOa57dw" target="_GMIX8IklEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yH70Y4klEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yH70ZIklEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yH70YYklEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yH70YoklEeqCs6_Zt3VV5Q" points="[65, 17, -129, -2]$[155, 17, -39, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yH9pkIklEeqCs6_Zt3VV5Q" id="(0.35,0.14)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yH9pkYklEeqCs6_Zt3VV5Q" id="(0.9069767441860465,0.5348837209302325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ES8MQIkmEeqCs6_Zt3VV5Q" type="4001" element="_ES2FoIkmEeqCs6_Zt3VV5Q" source="_GMIX8IklEeqCs6_Zt3VV5Q" target="_-uY-kIklEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ES8MQ4kmEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ES8MRIkmEeqCs6_Zt3VV5Q" x="-156" y="102"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ES8MQYkmEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ES8MQokmEeqCs6_Zt3VV5Q" points="[20, 2, -142, -443]$[150, 2, -12, -443]$[150, 420, -12, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IW4tYIknEeqCs6_Zt3VV5Q" type="4001" element="_IW0b8IknEeqCs6_Zt3VV5Q" source="_-uY-kIklEeqCs6_Zt3VV5Q" target="_ZHh1g4kmEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IW5UcIknEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IW5UcYknEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IW4tYYknEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IW4tYoknEeqCs6_Zt3VV5Q" points="[-6, 12, -1, -28]$[-6, 31, -1, -9]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KGtFMIknEeqCs6_Zt3VV5Q" type="4001" element="_KGseIIknEeqCs6_Zt3VV5Q" source="_ZHh1g4kmEeqCs6_Zt3VV5Q" target="_sxAhEIknEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KGtsQIknEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KGtsQYknEeqCs6_Zt3VV5Q" x="22" y="-13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KGtFMYknEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KGtFMoknEeqCs6_Zt3VV5Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KGvhcIknEeqCs6_Zt3VV5Q" id="(0.023255813953488372,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NYDEsIkoEeqCs6_Zt3VV5Q" type="4001" element="_NX-MMIkoEeqCs6_Zt3VV5Q" source="_ZHh1g4kmEeqCs6_Zt3VV5Q" target="_g_6pUIPcEeqXlKUduLqENg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NYDrwIkoEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NYDrwYkoEeqCs6_Zt3VV5Q" x="-587" y="-8"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NYDEsYkoEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NYDEsokoEeqCs6_Zt3VV5Q" points="[22, 0, 459, 804]$[130, 0, 567, 804]$[130, -809, 567, -5]$[-2, -809, 435, -5]$[-2, -804, 435, 0]$[-415, -804, 22, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Wi_KQ4koEeqCs6_Zt3VV5Q" type="4001" element="_Wi_KQIkoEeqCs6_Zt3VV5Q" source="__tJiUIkkEeqCs6_Zt3VV5Q" target="_sxAhEIknEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Wi_xUIkoEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Wi_xUYkoEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Wi_KRIkoEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Wi_KRYkoEeqCs6_Zt3VV5Q" points="[50, -7, -529, -539]$[292, -7, -287, -539]$[292, 538, -287, 6]$[529, 538, -50, 6]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_K5rvYokpEeqCs6_Zt3VV5Q" type="4001" element="_K5rIUIkpEeqCs6_Zt3VV5Q" source="_sxAhEIknEeqCs6_Zt3VV5Q" target="_daGzE4koEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_K5sWcIkpEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_K5sWcYkpEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_K5rvY4kpEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_K5rvZIkpEeqCs6_Zt3VV5Q" points="[6, 9, 2, -149]$[6, 144, 2, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_K5tkkIkpEeqCs6_Zt3VV5Q" id="(0.25,0.76)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YLs_EIkpEeqCs6_Zt3VV5Q" type="4001" element="_YLsYAIkpEeqCs6_Zt3VV5Q" source="_daGzE4koEeqCs6_Zt3VV5Q" target="_UuM9cIkpEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YLs_E4kpEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YLs_FIkpEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YLs_EYkpEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YLs_EokpEeqCs6_Zt3VV5Q" points="[-12, -1, -86, 1]$[75, -15, 1, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_YLuNMIkpEeqCs6_Zt3VV5Q" id="(1.0,0.8837209302325582)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_YLu0QIkpEeqCs6_Zt3VV5Q" id="(0.07,0.34)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_eautIYkpEeqCs6_Zt3VV5Q" type="4001" element="_eauGEIkpEeqCs6_Zt3VV5Q" source="_P3Zmk4kpEeqCs6_Zt3VV5Q" target="__tJiUIkkEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eautJIkpEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eautJYkpEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eautIokpEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eautI4kpEeqCs6_Zt3VV5Q" points="[8, 1, -4, 219]$[8, -224, -4, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_eawiUIkpEeqCs6_Zt3VV5Q" id="(0.20930232558139536,0.3488372093023256)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GKJosIkqEeqCs6_Zt3VV5Q" type="4001" element="_GKBF0IkqEeqCs6_Zt3VV5Q" source="_daGzE4koEeqCs6_Zt3VV5Q" target="_g_6pUIPcEeqXlKUduLqENg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GKJos4kqEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GKJotIkqEeqCs6_Zt3VV5Q" x="-420" y="227"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GKJosYkqEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GKJosokqEeqCs6_Zt3VV5Q" points="[-3, 8, 437, 1284]$[-412, 8, 28, 1284]$[-412, -1250, 28, 26]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GKLd4IkqEeqCs6_Zt3VV5Q" id="(0.13953488372093023,0.23255813953488372)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OWy6AIkqEeqCs6_Zt3VV5Q" type="4001" element="_OWyS8IkqEeqCs6_Zt3VV5Q" source="_UuM9cIkpEeqCs6_Zt3VV5Q" target="_qA-Xg4kpEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OWy6A4kqEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OWy6BIkqEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OWy6AYkqEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OWy6AokqEeqCs6_Zt3VV5Q" points="[-56, 9, -5, -66]$[-56, 45, -5, -30]$[-52, 45, -1, -30]$[-52, 55, -1, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OW1WQIkqEeqCs6_Zt3VV5Q" id="(1.0,0.82)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iZcI8IkqEeqCs6_Zt3VV5Q" type="4001" element="_iZX3gIkqEeqCs6_Zt3VV5Q" source="_qA-Xg4kpEeqCs6_Zt3VV5Q" target="_hoksuYkqEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iZcI84kqEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iZcwAIkqEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iZcI8YkqEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iZcI8okqEeqCs6_Zt3VV5Q" points="[-23, 7, -11, -117]$[-23, 90, -11, -34]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iZd-IIkqEeqCs6_Zt3VV5Q" id="(1.0,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vnLVk4kqEeqCs6_Zt3VV5Q" type="4001" element="_vnLVkIkqEeqCs6_Zt3VV5Q" source="_hoksuYkqEeqCs6_Zt3VV5Q" target="_nZ6ZMIkqEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vnLVlokqEeqCs6_Zt3VV5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vnL8oIkqEeqCs6_Zt3VV5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vnLVlIkqEeqCs6_Zt3VV5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vnLVlYkqEeqCs6_Zt3VV5Q" points="[35, -9, -86, -2]$[119, -15, -2, -8]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uiYzwIlWEeqm0fYUL6Uqjg" type="4001" element="_uhk7cIlWEeqm0fYUL6Uqjg" source="_nZ6ZMIkqEeqCs6_Zt3VV5Q" target="_nQnEsIlVEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uiZa0IlWEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uiZa0YlWEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uiYzwYlWEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uiYzwolWEeqm0fYUL6Uqjg" points="[2, 17, -10, -113]$[16, 111, 4, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uib3EIlWEeqm0fYUL6Uqjg" id="(0.3488372093023256,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_K094kIlXEeqm0fYUL6Uqjg" type="4001" element="_K08qcIlXEeqm0fYUL6Uqjg" source="_nQnEsIlVEeqm0fYUL6Uqjg" target="_8dnYgIlWEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_K0-foIlXEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_K0-foYlXEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_K094kYlXEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_K094kolXEeqm0fYUL6Uqjg" points="[-18, 1, 4, -104]$[-18, 87, 4, -18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_K1AU0IlXEeqm0fYUL6Uqjg" id="(0.5472972972972973,0.9864864864864865)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NpCisIlXEeqm0fYUL6Uqjg" type="4001" element="_NpB7oIlXEeqm0fYUL6Uqjg" source="_8dnYgIlWEeqm0fYUL6Uqjg" target="_MwGIgIlXEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NpDJwIlXEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NpDJwYlXEeqm0fYUL6Uqjg" x="-112" y="-12"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NpCisYlXEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NpCisolXEeqm0fYUL6Uqjg" points="[20, -1, -436, -1]$[436, -1, -20, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_N89u0IlYEeqm0fYUL6Uqjg" type="4001" element="_N89HwIlYEeqm0fYUL6Uqjg" source="_MwGIgIlXEeqm0fYUL6Uqjg" target="_GE4_UIlYEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_N89u04lYEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_N89u1IlYEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_N89u0YlYEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_N89u0olYEeqm0fYUL6Uqjg" points="[10, -10, 24, 1749]$[10, -1715, 24, 44]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N9ALEIlYEeqm0fYUL6Uqjg" id="(0.20930232558139536,0.27906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_W_gGUIlYEeqm0fYUL6Uqjg" type="4001" element="_W_ffQIlYEeqm0fYUL6Uqjg" source="_GE4_UIlYEeqm0fYUL6Uqjg" target="_TGOHoIlYEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_W_gGU4lYEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_W_gGVIlYEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_W_gGUYlYEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_W_gGUolYEeqm0fYUL6Uqjg" points="[0, 7, -78, 1]$[79, 2, 1, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_W_h7gIlYEeqm0fYUL6Uqjg" id="(1.0,0.3977272727272727)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_W_h7gYlYEeqm0fYUL6Uqjg" id="(0.1,0.3333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AW2B8IlZEeqm0fYUL6Uqjg" type="4001" element="_AWcZUIlZEeqm0fYUL6Uqjg" source="_8dnYgIlWEeqm0fYUL6Uqjg" target="_-pTiEIlYEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AW2B84lZEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AW2B9IlZEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AW2B8YlZEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AW2B8olZEeqm0fYUL6Uqjg" points="[-3, 8, -2, -40]$[-3, 40, -2, -8]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0O678IlaEeqm0fYUL6Uqjg" type="4001" element="_0O2qgIlaEeqm0fYUL6Uqjg" source="_qA-Xg4kpEeqCs6_Zt3VV5Q" target="_P3Zmk4kpEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0O6784laEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0O7jAIlaEeqm0fYUL6Uqjg" x="-427" y="-5"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0O678YlaEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0O678olaEeqm0fYUL6Uqjg" points="[-41, -14, 895, 0]$[-914, -14, 22, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0O8KEIlaEeqm0fYUL6Uqjg" id="(1.0,0.8837209302325582)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ppmGkIlbEeqm0fYUL6Uqjg" type="4001" element="_pplfgIlbEeqm0fYUL6Uqjg" source="_it78CIlbEeqm0fYUL6Uqjg" target="_l0QzwolbEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ppmGk4lbEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ppmGlIlbEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ppmGkYlbEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ppmGkolbEeqm0fYUL6Uqjg" points="[0, 0, -86, -14]$[35, 0, -51, -14]$[35, 11, -51, -3]$[71, 11, -15, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ppnUsIlbEeqm0fYUL6Uqjg" id="(1.0,0.62)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aW93wIlgEeqm0fYUL6Uqjg" type="4001" element="_aW2jAIlgEeqm0fYUL6Uqjg" source="_nZ6ZMIkqEeqCs6_Zt3VV5Q" target="_owXOwIkqEeqCs6_Zt3VV5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aW-e0IlgEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aW-e0YlgEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aW93wYlgEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aW93wolgEeqm0fYUL6Uqjg" points="[-13, 1, -192, 17]$[173, -7, -6, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aXAUAIlgEeqm0fYUL6Uqjg" id="(1.0,0.8372093023255814)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sB_vEolgEeqm0fYUL6Uqjg" type="4001" element="_sB_IAIlgEeqm0fYUL6Uqjg" source="_l5BluIlgEeqm0fYUL6Uqjg" target="_ojCU4IlgEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sB_vFYlgEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sB_vFolgEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sB_vE4lgEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sB_vFIlgEeqm0fYUL6Uqjg" points="[-9, 12, -2, -40]$[-9, 60, -2, 8]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wSpr8IlgEeqm0fYUL6Uqjg" type="4001" element="_wSpE4IlgEeqm0fYUL6Uqjg" source="_owXOwIkqEeqCs6_Zt3VV5Q" target="_l5BluIlgEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wSpr84lgEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wSpr9IlgEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wSpr8YlgEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wSpr8olgEeqm0fYUL6Uqjg" points="[-1, 20, -20, -586]$[-1, 568, -20, -38]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wSq6EIlgEeqm0fYUL6Uqjg" id="(0.59,0.76)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JIJl4IlhEeqm0fYUL6Uqjg" type="4001" element="_JII-0IlhEeqm0fYUL6Uqjg" source="_ojCU4IlgEeqm0fYUL6Uqjg" target="_EwykEIlhEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JIJl44lhEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JIJl5IlhEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JIJl4YlhEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JIJl4olhEeqm0fYUL6Uqjg" points="[1, 11, 0, -45]$[1, 58, 0, 2]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JIK0AIlhEeqm0fYUL6Uqjg" id="(0.5116279069767442,0.8604651162790697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VyejcIlhEeqm0fYUL6Uqjg" type="4001" element="_Vya5EIlhEeqm0fYUL6Uqjg" source="_ojCU4IlgEeqm0fYUL6Uqjg" target="_MwGIgIlXEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Vyejc4lhEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VyejdIlhEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VyejcYlhEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VyejcolhEeqm0fYUL6Uqjg" points="[22, 0, -206, 344]$[225, 0, -3, 344]$[225, -326, -3, 18]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_n2KLU4lhEeqm0fYUL6Uqjg" type="4001" element="_n2KLUIlhEeqm0fYUL6Uqjg" source="_-pTiEIlYEeqm0fYUL6Uqjg" target="_g_6pUIPcEeqXlKUduLqENg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_n2KyYIlhEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_n2KyYYlhEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_n2KLVIlhEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_n2KLVYlhEeqm0fYUL6Uqjg" points="[-16, 13, 1012, 1909]$[-1022, 13, 6, 1909]$[-1022, -1885, 6, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_n2LZcIlhEeqm0fYUL6Uqjg" id="(0.37209302325581395,0.18604651162790697)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_n2LZcYlhEeqm0fYUL6Uqjg" id="(0.13953488372093023,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_p9cn84lhEeqm0fYUL6Uqjg" type="4001" element="_p9cn8IlhEeqm0fYUL6Uqjg" source="_EwykEIlhEeqm0fYUL6Uqjg" target="_g_6pUIPcEeqXlKUduLqENg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_p9dPAIlhEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_p9dPAYlhEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_p9cn9IlhEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_p9cn9YlhEeqm0fYUL6Uqjg" points="[-10, 8, 1267, 2249]$[-1308, 8, -31, 2249]$[-1308, -2241, -31, 0]$[-1298, -2241, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_p9edIIlhEeqm0fYUL6Uqjg" id="(0.32558139534883723,0.20930232558139536)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-DoTE4lhEeqm0fYUL6Uqjg" type="4001" element="_-DoTEIlhEeqm0fYUL6Uqjg" source="_-pTiEIlYEeqm0fYUL6Uqjg" target="_8lVwI4lhEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-Do6IIlhEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-Do6IYlhEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-DoTFIlhEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-DoTFYlhEeqm0fYUL6Uqjg" points="[8, 3, -323, -112]$[330, 105, -1, -10]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-qCLw4lhEeqm0fYUL6Uqjg" type="4001" element="_-qCLwIlhEeqm0fYUL6Uqjg" source="_EwykEIlhEeqm0fYUL6Uqjg" target="_8lVwI4lhEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-qCy0IlhEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-qCy0YlhEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-qCLxIlhEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-qCLxYlhEeqm0fYUL6Uqjg" points="[16, -5, -187, 46]$[202, -51, -1, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-qDZ4IlhEeqm0fYUL6Uqjg" id="(0.09302325581395349,0.5348837209302325)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-qDZ4YlhEeqm0fYUL6Uqjg" id="(0.3488372093023256,0.813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__MWOoIlhEeqm0fYUL6Uqjg" type="4001" element="__MVnkIlhEeqm0fYUL6Uqjg" source="_8lVwI4lhEeqm0fYUL6Uqjg" target="_it78CIlbEeqm0fYUL6Uqjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__MWOo4lhEeqm0fYUL6Uqjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__MWOpIlhEeqm0fYUL6Uqjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__MWOoYlhEeqm0fYUL6Uqjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__MWOoolhEeqm0fYUL6Uqjg" points="[-2, -10, 12, 121]$[-18, -119, -4, 12]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
